name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: IbrahimAL22  # Replace with your GitHub username
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/IbrahimAL22/test:latest

      - name: Deploy to VPS via systemd using password
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: "164.92.204.82"
          username: "root"
          password: "A8z#K9v*Qp!X3t@L6w"
          script: |
            sudo systemctl restart flask_app.service
